# Generated by Django 2.2.16 on 2024-03-13 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rating', '0002_auto_20240313_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.SmallIntegerField(default=14, verbose_name='Возраст')),
                ('final_position', models.SmallIntegerField(blank=True, null=True)),
                ('full_season', models.BooleanField(default=True)),
                ('fired_season', models.BooleanField(default=False)),
                ('came_season', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachstatistic', to='rating.Player', verbose_name='Игрок')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachstatistic', to='rating.Season', verbose_name='Сезон')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachstatistic', to='rating.Team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Статистика тренера',
                'verbose_name_plural': 'Статистика тренеров',
                'ordering': ('-season',),
            },
        ),
        migrations.AddConstraint(
            model_name='coachstatistic',
            constraint=models.UniqueConstraint(fields=('name', 'team', 'season'), name='unique_coach_statistic'),
        ),
    ]
