# Generated by Django 2.2.16 on 2025-12-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='emblem_season',
            field=models.ImageField(blank=True, upload_to='emblem_season/', verbose_name='Эмблема сезона'),
        ),
    ]
