# Generated by Django 2.2.16 on 2025-05-20 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
        ('liga2_seasons_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTournamentWithoutPointsSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Место')),
                ('current_name', models.CharField(max_length=50, verbose_name='Текущее название')),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_tournament_without_points_second', to='rating.Season', verbose_name='Сезон')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_tournament_without_points_second', to='rating.Team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Команда второго доп т-ра без учета набранных ранее очков',
                'verbose_name_plural': 'Команды второго доп т-ра без учета набранных ранее очков',
            },
        ),
        migrations.AddField(
            model_name='teamintable1gr',
            name='additional_tournament_without_points_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liga2_seasons_app.AdditionalTournamentWithoutPointsSecond', verbose_name='Участие во втором доп т-ре без учета ранее набранных очков'),
        ),
        migrations.AddField(
            model_name='teamintable2gr',
            name='additional_tournament_without_points_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liga2_seasons_app.AdditionalTournamentWithoutPointsSecond', verbose_name='Участие во втором доп т-ре без учета ранее набранных очков'),
        ),
    ]
