# Generated by Django 2.2.16 on 2026-01-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga2_seasons_app', '0002_auto_20250520_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptiontable',
            name='description_season',
            field=models.TextField(blank=True, verbose_name='Описание сезона'),
        ),
    ]
