# Generated by Django 2.2.16 on 2024-07-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalkeeperStatisticLiga2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.SmallIntegerField(default=14, verbose_name='Возраст')),
                ('game', models.SmallIntegerField(default=1, verbose_name='Игры')),
                ('goal_against', models.SmallIntegerField(default=0, verbose_name='Голы')),
                ('penalty', models.SmallIntegerField(default=0, verbose_name='Штраф')),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goalkeeperstatistic_liga2', to='rating.Player', verbose_name='Игрок')),
                ('position', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goalkeeperstatistic_liga2', to='rating.Position', verbose_name='Позиция')),
                ('season', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goalkeeperstatistic_liga2', to='rating.Season', verbose_name='Сезон')),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goalkeeperstatistic_liga2', to='rating.Team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Статистика Вратаря в первой лиге',
                'verbose_name_plural': 'Статистика Вратарей в первой лиге',
                'ordering': ('-season',),
            },
        ),
        migrations.AddConstraint(
            model_name='goalkeeperstatisticliga2',
            constraint=models.UniqueConstraint(fields=('name', 'team', 'season'), name='unique_goalkeeper_statistic_liga2'),
        ),
    ]
